### ISSUE TITLE
Website does not accept HTTPS connections

### ISSUE THREAD

**Issue by xDazld** [grallucas/maic#6]
Not having a secure connection available is a security risk, especially since the MAIC website has code downloads.
The easiest way I can think of to fix would be to [set the MAIC domain as a custom name for this repository](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain), so you can just use GitHub's hosting, which supports HTTPS.

**Comment by Benja-Pauls** [comment]
Thank you for the note -- we were thinking of hosting the website on AWS due to GitHub Page's storage policies for hosting large models locally, but we enjoy the easy-update features of pushing website backend updates directly to a repo ha ha.

We'll probably migrate back to GitHub Pages and follow your advice of attaching our existing domain to this repository -- we'll simply host the larger models we provide for workshops in an S3 AWS instance which we can securely call from the website.

Hoping to have this fix pushed out by EOW

**Comment by xDazld** [comment]
As a possible solution to model hosting, [Hugging Face](https://huggingface.co/) provides free hosting for AI models. Could you upload the models there and link to the downloads from the MAIC site?
